### ISSUE TITLE
JSON data is not showing up

### ISSUE THREAD

**Issue by sergsalo** [ealsur/HTTPDataCollectorAPI#2]
JSON data is not showing up in OMS search portal. I see that I am able to successfully post, because it creates a type that I specified, but the body of the data record in OMS shows only two properties:
{
   TimeGenerated: "....",
   SourceSystem: RestAPI
 }

the object I posted though looks like:

public class OMSEvent
    {
        public int Id { get; set; }
        public double Value { get; set; }
        public DateTime Timestamp { get; set; }
    }

Code is very simple:

 var message = new OMSEvent
                    {
                        Id = count,
                        Value = v,
                        Timestamp = DateTime.UtcNow
                    };
await mCollector.Collect("OMSEvent", message);

I thought I should be able to search in my properties....

**Comment by ealsur** [comment]
Hi! Sadly this package makes sure that the payload is delivered, attribute indexing takes part on the Log Analytics side and, in my experience, for first-time processing it can take a while but they will eventually show up.

Basically the package will make sure that the Log Analytics receives the data correctly and returns an [Accepted response code](https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-collector-api#return-codes). Log Analytics then processes internally the data at its own pace.

We are consuming this package internally in all our projects and it works but it can take some time for first-time data types, quoting the documentation:

> The HTTP status code 202 means that the request has been accepted for processing, but processing has not yet finished. This indicates that the operation completed successfully.

**Comment by sergsalo** [comment]
got it, thanks!!!

**Comment by sergsalo** [comment]
this helped to speed things out.... just a reference.
http://blogs.catapultsystems.com/cfuller/archive/2016/09/30/no-data-appearing-when-using-the-log-analytics-http-data-collector-api/

**Comment by ealsur** [comment]
@sergsalo There is a reported issue on the OMS portal with browser cache that they are working on :)
