### ISSUE TITLE
No support for time-generated-field header

### ISSUE THREAD

**Issue by sergsalo** [ealsur/HTTPDataCollectorAPI#3]
According to this article https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-collector-api#create-a-request time-generated-field can be used to specify actual data timestamp.

Would be very useful for my scenario.

**Comment by sergsalo** [comment]
created pull request https://github.com/ealsur/HTTPDataCollectorAPI/pull/4

**Comment by ealsur** [comment]
Great addition, thanks a lot!

**Comment by ealsur** [comment]
Nuget package has been updated
