### ISSUE TITLE
Authorization header content length

### ISSUE THREAD

**Issue by Votok** [ealsur/HTTPDataCollectorAPI#6]
When creating request header Authorization signature there is a jsonPayload.length used now.
However the request uses UTF8 encoded content (sometimes different) length and it results in azure returning 403 Forbidden response.

For example if jsonPayload contains some special characters such as 'ě', then it fails.

Please use the same (encoded) content length also when building signature.

**Comment by ealsur** [comment]
Wrapped and published in nuget as version 1.0.4. 
Thanks for the PR!
